import uuid as uuid_module
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Sequence,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import CITEXT, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base

# One sequence shared by every syncable table, so a client holds a single
# integer cursor that orders workouts, activities and settings together. Bumped
# on insert and on update; see sync.next_seq().
RECORD_SEQ = Sequence("record_seq", metadata=Base.metadata)


def new_uuid() -> uuid_module.UUID:
    return uuid_module.uuid4()


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid_module.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_uuid)
    email: Mapped[str] = mapped_column(CITEXT, unique=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class UserSession(Base):
    """A login session. Only the sha256 of the cookie value is ever stored."""

    __tablename__ = "sessions"

    token_hash: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    user_agent: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (Index("ix_sessions_user_id", "user_id"),)


class PasswordReset(Base):
    """One emailed reset code. Only a keyed hash of the code is ever stored.

    `consumed_at` means "no longer usable" rather than "was used": a successful
    reset stamps it, and so does issuing a replacement code. The row is kept
    either way, because the per-hour cap counts rows — deleting spent ones would
    quietly erase the evidence the throttle runs on.
    """

    __tablename__ = "password_resets"

    id: Mapped[uuid_module.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=new_uuid)
    user_id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    code_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    __table_args__ = (Index("ix_password_resets_user_created", "user_id", "created_at"),)


class UserSettings(Base):
    """The rider profile — FTP and weight — as one record per user.

    One row rather than a key/value table: the whole profile is written from a
    single settings screen, so a per-field merge would buy nothing and would cost
    a cursor entry per field. There is no `deleted_at`: settings are replaced,
    never deleted, and the row goes with the account through the FK cascade.
    """

    __tablename__ = "settings"

    user_id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    # ftp, weight. Validated by schemas.RiderSettings on the way in.
    settings: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    seq: Mapped[int] = mapped_column(BigInteger, nullable=False)
    client_updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class Workout(Base):
    """A custom workout. `id` is generated by the client so it survives offline creation.

    The primary key is (user_id, id), not id alone. Ids arrive from clients, so a
    global key would let one user's push collide with another user's row — a
    constraint violation that both breaks the request and confirms the id exists.
    Scoping the key makes that structurally impossible.
    """

    __tablename__ = "workouts"

    id: Mapped[uuid_module.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    user_id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), primary_key=True, nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Parsed form, exactly as held in IndexedDB. Workout.parse() accepts both ZWO
    # and FIT courses, so ZWO is not a universal source form.
    workout: Mapped[dict] = mapped_column(JSONB, nullable=False)
    zwo: Mapped[str | None] = mapped_column(Text)

    # Server clock. Sync cursor ordering only.
    seq: Mapped[int] = mapped_column(BigInteger, nullable=False)
    # Client clock. Last-write-wins comparison only. Kept separate so a device
    # with a skewed clock cannot skip records out of the cursor.
    client_updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (Index("ix_workouts_user_seq", "user_id", "seq"),)


class Activity(Base):
    """A completed ride. The FIT blob itself lives in Spaces, not here."""

    __tablename__ = "activities"

    id: Mapped[uuid_module.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    user_id: Mapped[uuid_module.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), primary_key=True, nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False, default="")
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    duration_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # avgPower, np, tss, ftp, trace, plan, avgHeartRate, status
    summary: Mapped[dict] = mapped_column(JSONB, nullable=False)

    fit_key: Mapped[str | None] = mapped_column(Text)
    # NULL means the blob is not confirmed present. A row with fit_key set and
    # this NULL is a resumable upload, not a broken record.
    fit_uploaded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    fit_size_bytes: Mapped[int | None] = mapped_column(Integer)

    seq: Mapped[int] = mapped_column(BigInteger, nullable=False)
    client_updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (Index("ix_activities_user_seq", "user_id", "seq"),)
